using UnityEngine;
using System.Collections;
using System;

public enum MessengerEventsEnum : int
{
	//CAR
	CHANGE_EXT_BODY_COLOR = 0,
	CHANGE_INT_BODY_COLOR = 18,
	CHANGE_GLOBAL_RLINE = 1,
	CHANGE_GLOBAL_SUNROOF = 2,
	CHANGE_INT_NAVIGATOR = 3,
	CHANGE_INT_UPHOLSTERY = 4,
	CHANGE_INT_POS = 5,
	CHANGE_GLOBAL_POS = 6,
	VERSION_BUTTON_PRESSED = 7,
	CHANGE_EXT_TIRES = 8,
	CHANGE_VERSION = 9,
	BUTTON_SUNROOF_PRESSED = 10,
	CHANGE_NIGHT = 19,
	CHANGE_AMBILIGHT = 20,
	BUTTON_NIGHT_PRESSED = 21,
	SWITCH_AMBILIGHT = 22,
	BUTTON_SWITCH_AMBILIGHT_PRESSED = 23,

	//UI
	SHOW_MENU = 11,
	HIDE_MENU = 12,
    MOVING_MENU = 13,
    STOP_MENU = 14,
	GO_TO_PANEL = 15,
	END_GO_TO_PANEL = 16,

	//CAMERA
	MOVE_CAMERA = 17
}
